### PR TITLE
Improved Docs.

### PR DESCRIPTION
**Pull request by helpinubcomgr8**
HI

### CODE REVIEW

**Comment by IceCereal** [comment]
This PR does absolutely nothing.

**Comment by helpinubcomgr8** [comment]
Actually I not a person with person with that high level of coding
experience to change in your code, i partially understand it ( partially is
a big word).
I was working on a PR for Hacktoberfest 2020. I would request to ignore the
PR. Or if you wish  mark it invalid. I am sorry for disturbing you. I am
just learning to do PR, so consider it a learner's experiment to gain
experience.

Thank you.
India will beat Covid.

**Comment by IceCereal** [comment]
Understandable. However, please don't waste maintainers' time at the expense of your learning.

Instead, I'd suggest you go through this: https://github.com/search?q=label%3Ahacktoberfest+state%3Aopen+no%3Aassignee+is%3Aissue&type=Issues.

**Comment by helpinubcomgr8** [comment]
Sure, No maintainer's time will be wasted due to me. Thanks.

If u just had ignored or added the change their would have been no problem.
Your website is already down, a small hastag would not have cost you a
fortune.
I would have gotten a T shirt or something due to that. Chillax.
It was delightful talking to you.

**Pull request closed without merging**
