### PR TITLE
added jekyll and created few components

### PR DESCRIPTION
**Pull request by bhansa**
#65 

Please have a look.
@Rohithgilla12

### CODE REVIEW

**Comment by Rohithgilla12** [comment]
Hey, @bhansa Thanks a lot for this.
Honestly, I have no idea with Jekyll pages. But this seems super smooth and modular.
This website CI/CD is done using Netlify. 

Do you think initially trying for branch deploy and see if it's working, then we can merge it to master? Because currently, many people are viewing the site live, don't want to break anything.
I just came across [this](https://www.netlify.com/blog/2015/10/28/a-step-by-step-guide-jekyll-3.0-on-netlify/), if these are the steps needed, once you push to another branch I will create branch deploy for that with these in the `netlify.toml` file.

P.S: Thanks a lot for taking your time

**Comment by bhansa** [comment]
Hi, I am trying to get a preview for this commit, once done we can validate.

**Comment by Rohithgilla12** [comment]
We can’t get preview for this commit the master branch deploy config is different.
I can do this for you, I’ll create a new empty branch. Create a PR to that branch, I’ll setup a branch deploy for that so that you can validate your commit. 
Or let me know if you have any other ideas

**Comment by bhansa** [comment]
Hi, Sorry for not being clear.
I have setup a preview on netlify here:
https://5eac6460108607f23b36263f--stoic-booth-220816.netlify.app/

One major change which I have done is removing the live folder, I have moved everything to root directory.

**Comment by Rohithgilla12** [comment]
Wow that’s awesome.
I’ll share the link with the Achal who started it and I’ll get back to you soon.
That’s super fast btw deploy thing

**Comment by Rohithgilla12** [comment]
Hey, thanks.
Looks awesome and good.
How should we proceed like merging into master, configuring netlify?

**Comment by bhansa** [comment]
We need to merge it to master and in netlify we need to change some deployment rules I guess.
build: jekyll build
folder: _site

**Comment by Rohithgilla12** [comment]
Okay, gotcha.
Let me try fixing the merge conflicts we have.

**Comment by IceCereal** [comment]
@bhansa Hey, I'm reverting back to one commit ago. Can you use `git mv` instead of moving the files directly. This will preserve the commit history.

**Comment by IceCereal** [comment]
Also, it seems that you haven't pulled the latest commit. I don't see the `zones.html`. If you could include that, that'd be great. Thank you!!!

**Comment by bhansa** [comment]
Hi, I will have to generate the jekyll project again and create folders for `layout` and `includes` if I revert back the code. I can add the zones.html file in code manually.
Does that work?

**Comment by IceCereal** [comment]
Yes, that seems fine. As long as the commit history is preserved, it can be merged.

**Pull request merged**
